[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "10.16.3"
  RUBY_VERSION = "2.6.2"
  REACT_APP_CONTEXT = "production"
  REACT_APP_BINARY_OPTIONS_ENABLED = "false"

[context.branch-deploy.environment]
  REACT_APP_BINARY_OPTIONS_ENABLED = "true"
  REACT_APP_CONTEXT = "staging"

